---

- name: Starting shibboleth container
  kolla_docker:
    action: "start_container"
    common_options: "{{ docker_common_options }}"
    image: "{{ shibboleth_image_full }}"
    name: "shibboleth"
    ipc_mode: "host"
    privileged: True
    volumes:
      - "{{ node_config_directory }}/shibboleth/:{{ container_config_directory }}/:ro"
      - "kolla_logs:/var/log/kolla/"
      - "/etc/localtime:/etc/localtime:ro"
      - "/dev/:/dev/"
      - "/run/:/run/:shared"
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "/lib/modules:/lib/modules:ro"
      - "/sys/kernel/config:/configfs"

  when:
    - inventory_hostname in groups['control']
